// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL-f1kPYXtXYkhLLJu1F2b9h9RU3ldpfo',
    appId: '1:580206280400:web:f53fa43bf2d6d5e992a8d5',
    messagingSenderId: '580206280400',
    projectId: 'nddahelper',
    authDomain: 'nddahelper.firebaseapp.com',
    storageBucket: 'nddahelper.firebasestorage.app',
    measurementId: 'G-C8EEN29558',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5i2c6nPPUsyknMqnHhTFZrehdECztDJ4',
    appId: '1:580206280400:android:18c65f73a128b02f92a8d5',
    messagingSenderId: '580206280400',
    projectId: 'nddahelper',
    storageBucket: 'nddahelper.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVrdClLNR01tkfdu1RD4lPIBaImhLrJ8A',
    appId: '1:580206280400:ios:8785c04d89a9dd3b92a8d5',
    messagingSenderId: '580206280400',
    projectId: 'nddahelper',
    storageBucket: 'nddahelper.firebasestorage.app',
    iosBundleId: 'com.clinpharm.kz',
  );
}
